pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps{
                deleteDir()
            }

        }
        stage("Clone Repo"){
             steps{
                    sh "git clone https://github.com/mouzong/ecommerce-api.git"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'here comes the dark coder'
                sh 'sudo ./jenkins/scripts/deliver.sh'
            }
        }
    }
}